-- \i /home/pachv/Code/glawe-fake-api/Database/clear_db.sql 

                    drop table if exists machines,
                                shop_total,
                                worker,
                                worker_actions,
                                worker_metrics,
                                machine_types,
                                sensors_by_types,
                                worker_to_machine,
                                sensors,
                                machine_actions,
                                production,
                                user_admin,
                                target_values,
                                production_total,
                                report_models,
                                report_blocks,
                                generated_reports,
                                shop,
                                machine_metrics,
                                alerts,
                               machine_workplace;